### ISSUE TITLE
Viewport Shader - How to use ?

### ISSUE THREAD

**Issue by SheepDomination** [Byron/bsuite#3]
Hi, how do you use the Viewport shaders, I loaded one of the example scenes but the effect of the shader is not seen in the viewport.

**Comment by Byron** [comment]
In the attached screenshot you see how I was doing it. The trick seems to be to hit **6** on the keyboard to show textures.
![screen shot 2016-05-18 at 10 43 28](https://cloud.githubusercontent.com/assets/63622/15352634/6533db2e-1ce5-11e6-8616-8e1383972162.png)

PS: in the bottom-right you see the name of the scene that I have loaded. Even though I am closing the issue, feel free to comment here in case it persists.

**Comment by SheepDomination** [comment]
I don't have the shaders.bundle installed and I installed 2010 x64 version of your tools plugin ?

**Comment by Byron** [comment]
It's a separate plugin as you can see, and I hope the shader plugin file (.dll on windows, .so on linux, .bundle on osx) is part of the downloadable content. If it is not, I am afraid that I am not able anymore to compile plugins anymore.
In any case, if the plugin is in your PLUGIN_PATH, it would have been loaded automatically. So it looks like it's just not there.

**Comment by SheepDomination** [comment]
It appears you are right, there is no shaders.bundle with the 2010 x64 compressed file of your tools, only one dll file, unfortunately.  I was looking forward to trying your tool, bummer.
